### ISSUE TITLE
getInstanceについて

### ISSUE THREAD

**Issue by ys-practice** [MasayoshiAizawa/Kadai#12]
https://github.com/MasayoshiAizawa/Kadai/blob/3729a3145dc2783e633bbba00073487361e0ae07/Kadai8.java#L13-L15
ちょっとややこしい話になりますが、
①
Javaで「getInstance()」というメソッドは
よく『シングルトンパターン』というのを実現するために使われたりします。
シングルトンの説明は省きますが、
シングルトンパターンの常識ではgetInstance()を呼び出した際に
期待されるのは常に同一のインスタンスだったりします。
なので、その論理から行くと上記コードのように複数のインスタンスを作成
するような書き方はしません。

②
で、今回ですが、、CalendarのgetInstance()の場合はシングルトンパターンじゃなく
呼ばれるたびにnewしたインスタンスを返します。

なので、プログラムとしては間違った実装ではないのですが、
見る人によっては「シングルトンパターンを理解してないのかな」
と誤解されるかもしれません。

getIncetance()というメソッドにであった場合には
どういうインスタンスが取得されるのか注意して使いましょう。

※どのみちCalendarはスレッドセーフじゃないのでシングルトンパターンどころではなかったりしますが。。

**Comment by MasayoshiAizawa** [comment]
ご指摘ありがとうございます。
シングルトンパターンやスレッドセーフについて理解が足りませんでした。確認いたします。
————————————
システム開発部　逢澤正義
————————————
