### ISSUE TITLE
文字列の比較

### ISSUE THREAD

**Issue by ys-practice** [MasayoshiAizawa/Kadai#3]
https://github.com/MasayoshiAizawa/Kadai/blob/f7d0ba3e031a8af639103b5fe983f4f54cbc4d61/kadai/kadai1.java#L20

String文字列の比較をするにはequals()メソッドを使いましょう。
Stringは参照型なので関係演算子「==」で比較すると参照先の比較になりますので、
この式は常にfalseになります。

**Comment by MasayoshiAizawa** [comment]
ご指摘ありがとうございます。
確認して改善してみます。

————————————
システム開発部　逢澤正義
————————————

**Comment by ys-practice** [comment]
確認しましたのでクローズします。
